@startuml
left to right direction
:Ciudadano: as ciu
:Ciudadano extranjero: as ext

ciu -- (Registrar entrada)
ciu <|- ext

ext -- (Tomar huellas)

(Registrar entrada) <. (Tomar huellas): <<extend>>
@enduml